using System;

namespace System.CodeDom.Compiler
{
	/// <summary>Identifies code generated by a tool. This class cannot be inherited.</summary>
	// Token: 0x0200067B RID: 1659
	[AttributeUsage(AttributeTargets.All, Inherited = false, AllowMultiple = false)]
	[global::__DynamicallyInvokable]
	public sealed class GeneratedCodeAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.CodeDom.Compiler.GeneratedCodeAttribute" /> class specifying the name and version of the tool that generated the code.</summary>
		/// <param name="tool">The name of the tool that generated the code.</param>
		/// <param name="version">The version of the tool that generated the code.</param>
		// Token: 0x06003D1F RID: 15647 RVA: 0x000FB421 File Offset: 0x000F9621
		[global::__DynamicallyInvokable]
		public GeneratedCodeAttribute(string tool, string version)
		{
			this.tool = tool;
			this.version = version;
		}

		/// <summary>Gets the name of the tool that generated the code.</summary>
		/// <returns>The name of the tool that generated to code.</returns>
		// Token: 0x17000E90 RID: 3728
		// (get) Token: 0x06003D20 RID: 15648 RVA: 0x000FB437 File Offset: 0x000F9637
		[global::__DynamicallyInvokable]
		public string Tool
		{
			[global::__DynamicallyInvokable]
			get
			{
				return this.tool;
			}
		}

		/// <summary>Gets the version of the tool that generated the code.</summary>
		/// <returns>The version of the tool that generated the code.</returns>
		// Token: 0x17000E91 RID: 3729
		// (get) Token: 0x06003D21 RID: 15649 RVA: 0x000FB43F File Offset: 0x000F963F
		[global::__DynamicallyInvokable]
		public string Version
		{
			[global::__DynamicallyInvokable]
			get
			{
				return this.version;
			}
		}

		// Token: 0x04002C82 RID: 11394
		private readonly string tool;

		// Token: 0x04002C83 RID: 11395
		private readonly string version;
	}
}
