using System;
using System.Reflection;

namespace System.Runtime.InteropServices
{
	/// <summary>Provides a callback mechanism for the type library converter to inform the caller of the status of the conversion, and involve the caller in the conversion process itself.</summary>
	// Token: 0x0200096D RID: 2413
	[Guid("F1C3BF76-C3E4-11d3-88E7-00902754C43A")]
	[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
	[ComVisible(true)]
	public interface ITypeLibImporterNotifySink
	{
		/// <summary>Notifies the caller that an event occured during the conversion of a type library.</summary>
		/// <param name="eventKind">An <see cref="T:System.Runtime.InteropServices.ImporterEventKind" /> value indicating the type of event.</param>
		/// <param name="eventCode">Indicates extra information about the event.</param>
		/// <param name="eventMsg">A message generated by the event.</param>
		// Token: 0x0600624C RID: 25164
		void ReportEvent(ImporterEventKind eventKind, int eventCode, string eventMsg);

		/// <summary>Asks the user to resolve a reference to another type library.</summary>
		/// <param name="typeLib">The object implementing the <see langword="ITypeLib" /> interface that needs to be resolved.</param>
		/// <returns>The assembly corresponding to <paramref name="typeLib" />.</returns>
		// Token: 0x0600624D RID: 25165
		Assembly ResolveRef([MarshalAs(UnmanagedType.Interface)] object typeLib);
	}
}
