using System;

namespace System.Deployment.Internal.Isolation
{
	// Token: 0x02000694 RID: 1684
	internal enum IIDENTITYAUTHORITY_DEFINITION_IDENTITY_TO_TEXT_FLAGS
	{
		// Token: 0x04002219 RID: 8729
		IIDENTITYAUTHORITY_DEFINITION_IDENTITY_TO_TEXT_FLAG_CANONICAL = 1
	}
}
